copyright: Copyright &copy; 2016 - 2026 MapGallery B.V.
site_name: MapGallery documentatie
site_url: https://docs.mapgallery.eu/
repo_url: https://github.com/mapgallery/documentation
edit_uri: edit/main/docs/
extra:
  analytics:
    provider: plausible
    domain: docs.mapgallery.eu
  homepage: https://mapgallery.eu
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:info@mapgallery.eu
    - icon: fontawesome/brands/github
      link: https://github.com/mapgallery
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/mapgallery
  version:
    provider: mike
extra_css:
  - assets/css/extra.css
markdown_extensions:
  - abbr
  - admonition
  - meta
  - pymdownx.keys
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - tables
  - toc
nav:
  - Introductie:
      - index.md
      - application.md
      - questions.md
  - Gebruiker:
      - manual/index.md
      - manual/map/index.md
      - manual/search/index.md
      - Kaartlagen:
          - manual/layers/index.md
          - manual/layers/import.md
          - manual/layers/filter.md
          - manual/layers/metadata.md
      - Collecties:
        - manual/collections/index.md
        - manual/favorites/index.md
      - Locatie-informatie:
          - manual/location/index.md
          - manual/location/selection.md
      - manual/streetview/index.md
      - manual/draw/index.md
      - manual/export/index.md
      - manual/menu/index.md
      - manual/troubleshooting/index.md
  - Beheerder:
      - admin/index.md
      - admin/dashboard.md
      - Toegang:
          - admin/access/users.md
          - admin/access/groups.md
      - Opties:
          - admin/options/mapinfo.md
          - admin/options/views.md
          - admin/options/searches.md
      - admin/collections.md
      - admin/layers.md
      - admin/services.md
      - admin/application.md
  - Changelog:
      - changelog/index.md
      - changelog/v7.md
plugins:
  - macros:
      include_dir: includes
  - material-plausible
  - search
  - social
  - tags
theme:
  name: material
  favicon: assets/favicon.png
  features:
    - content.action.edit
    - content.action.view
#    - navigation.expand
    - navigation.path
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - search.suggest
    - search.highlight
    - toc.follow
#    - toc.integrate
  language: nl
  logo: assets/logo.png
  palette:
    # Volgt de instelling van het besturingssysteem
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Lichte modus
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Donkere modus
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Systeeminstelling volgen
validation:
  links:
    absolute_links: relative_to_docs
watch:
  - includes
