name: Branch Release Docs

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches-ignore:
      - 'main'

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - name: Setup Docs Deploy
        run: |
          git config --global user.name "Mike"
          git config --global user.email "mike@mapgallery.eu"
      - name: Build Docs Website
        run: mike deploy --push --update-aliases ${{ github.ref_name }} latest
